{-----------------------------------------------------------------------------
 Unit Name: Consts
 Author:    Dancemammal
 Purpose:  Constants for CDBurners
 History:  First Pass
-----------------------------------------------------------------------------}

unit DeviceConsts;

interface

const

  MAX_DATABLOCKS = 16;

  {-----------------------------------------------------------------------------
    Const: List of Vendor Names from T10
    Author:    Paul Fisher
    Date:      16-Feb-2005
    Arguments: None
    Result:    None
  -----------------------------------------------------------------------------}

  ScsiVendorNameList =
    '"0B4C=MOOSIK Ltd.",' +
    '"2AI=2AI (Automatisme et Avenir Informatique)",' +
    '"3M=3M Company",' +
    '"3PARdata=3PARdata, Inc.",' +
    '"A-Max=A-Max Technology Co., Ltd",' +
    '"Acer=Acer, Inc.",' +
    '"ACL=Automated Cartridge Librarys, Inc.",' +
    '"Acuid=Acuid Corporation Ltd.",' +
    '"AcuLab=AcuLab, Inc. (Tulsa, OK)",' +
    '"ADAPTEC=Adaptec",' +
    '"ADIC=Advanced Digital Information Corporation",' +
    '"ADSI=Adaptive Data Systems, Inc. (a Western Digital subsidiary)",' +
    '"ADTX=ADTX Co., Ltd.",' +
    '"ADVA=ADVA Optical Networking AG",' +
    '"AERONICS=Aeronics, Inc.",' +
    '"AGFA=AGFA",' +
    '"AIPTEK=AIPTEK International Inc.",' +
    '"AMCODYNE=Amcodyne",' +
    '"Amphenol=Amphenol",' +
    '"ANAMATIC=Anamartic Limited (England)",' +
    '"Ancor=Ancor Communications, Inc.",' +
    '"ANCOT=ANCOT Corp.",' +
    '"ANDATACO=Andataco  (now nStor)",' +
    '"andiamo=Andiamo Systems, Inc.",' +
    '"ANRITSU=Anritsu Corporation",' +
    '"ANTONIO=Antonio Precise Products Manufactory Ltd.",' +
    '"APPLE=Apple Computer, Inc.",' +
    '"ARCHIVE=Archive",' +
    '"ARIO=Ario Data Networks, Inc.",' +
    '"ARISTOS=Aristos Logic Corp.",' +
    '"ARK=ARK Research Corporation",' +
    '"ARTECON=Artecon Inc.  (Obs. - now Dot Hill)",' +
    '"ASACA=ASACA Corp.",' +
    '"ASC=Advanced Storage Concepts, Inc.",' +
    '"ASPEN=Aspen Peripherals",' +
    '"AST=AST Research",' +
    '"ASTK=Alcatel STK A/S",' +
    '"AT&T=AT&T",' +
    '"ATA=SCSI / ATA Translator Software (Organization Not Specified",' +
    '"ATARI=Atari Corporation",' +
    '"ATG CYG=ATG Cygnet Inc.",' +
    '"ATL=Quantum|ATL Products",' +
    '"ATTO=ATTO Technology Inc.",' +
    '"ATX=Alphatronix",' +
    '"AVC=AVC Technology Ltd",' +
    '"AVR=Advanced Vision Research",' +
    '"BALLARD=Ballard Synergy Corp.",' +
    '"BAROMTEC=Barom Technologies Co., Ltd.",' +
    '"BDT=Buero- und Datentechnik GmbH & Co.KG",' +
    '"BENQ=BENQ Corporation.",' +
    '"BERGSWD=Berg Software Design",' +
    '"BEZIER=Bezier Systems, Inc.",' +
    '"BHTi=Breece Hill Technologies",' +
    '"BIR=Bio-Imaging Research, Inc.",' +
    '"BiT=BiT Microsystems (obsolete, new ID: BITMICRO)",' +
    '"BITMICRO=BiT Microsystems, Inc.",' +
    '"BlueArc=BlueArc Corporation",' +
    '"BNCHMARK=Benchmark Tape Systems Corporation",' +
    '"BoxHill=Box Hill Systems Corporation  (Obs. - now Dot Hill)",' +
    '"BREA=BREA Technologies, Inc.",' +
    '"Broadcom=Broadcom Corporation",' +
    '"BROCADE=Brocade Communications Systems, Incorporated",' +
    '"BULL=Bull Peripherals Corp.",' +
    '"BUSLOGIC=BusLogic Inc.",' +
    '"CalComp=CalComp, A Lockheed Company",' +
    '"CALIPER=Caliper (California Peripheral Corp.)",' +
    '"CAMBEX=Cambex Corporation",' +
    '"CAMEOSYS=Cameo Systems Inc.",' +
    '"CANDERA=Candera Inc.",' +
    '"CAPTION=CAPTION BANK",' +
    '"CAST=Advanced Storage Tech",' +
    '"CDC=Control Data or MPI",' +
    '"CDP=Columbia Data Products",' +
    '"CenData=Central Data Corporation",' +
    '"Cereva=Cereva Networks Inc.",' +
    '"CERTANCE=Certance",' +
    '"CHEROKEE=Cherokee Data Systems",' +
    '"CHINON=Chinon",' +
    '"CIE&YED=YE Data, C.Itoh Electric Corp.",' +
    '"CIPHER=Cipher Data Products",' +
    '"Ciprico=Ciprico, Inc.",' +
    '"CIRRUSL=Cirrus Logic Inc.",' +
    '"CISCO=Cisco Systems, Inc.",' +
    '"CLOVERLF=Cloverleaf Communications, Inc",' +
    '"CMD=CMD Technology Inc.",' +
    '"CMTechno=CMTech",' +
    '"CNGR SFW=Congruent Software, Inc.",' +
    '"CNSi=Chaparral Network Storage, Inc.",' +
    '"CNT=Computer Network Technology",' +
    '"COBY=Coby Electronics Corporation, USA",' +
    '"COGITO=Cogito",' +
    '"COMPAQ=Compaq Computer Corporation (now HP)",' +
    '"COMPELNT=Compellent Technologies, Inc.",' +
    '"COMPORT=Comport Corp.",' +
    '"COMPSIG=Computer Signal Corporation",' +
    '"COMPTEX=Comptex Pty Limited",' +
    '"CONNER=Conner Peripherals",' +
    '"CORE=Core International, Inc.",' +
    '"COWON=COWON SYSTEMS, Inc.",' +
    '"CPL=Cross Products Ltd",' +
    '"CPU TECH=CPU Technology, Inc.",' +
    '"CREO=Creo Products Inc.",' +
    '"CROSFLD=Crosfield Electronics (now FujiFilm Electonic Imaging Ltd)",' +
    '"CROSSRDS=Crossroads Systems, Inc.",' +
    '"CSCOVRTS=Cisco - Veritas",' +
    '"CSM, INC=Computer SM, Inc.",' +
    '"CYBERNET=Cybernetics",' +
    '"Cygnal=Dekimo",' +
    '"DALSEMI=Dallas Semiconductor",' +
    '"Data Com=Data Com Information Systems Pty. Ltd.",' +
    '"DATABOOK=Databook, Inc.",' +
    '"DATACOPY=Datacopy Corp.",' +
    '"DataCore=DataCore Software Corporation",' +
    '"DATAPT=Datapoint Corp.",' +
    '"DDN=DataDirect Networks, Inc.",' +
    '"DEC=Digital Equipment Corporation (now HP)",' +
    '"DEI=Digital Engineering, Inc.",' +
    '"DELL=Dell Computer Corporation",' +
    '"DELPHI=Delphi Data Div. of Sparks Industries, Inc.",' +
    '"DENON=Denon/Nippon Columbia",' +
    '"DenOptix=DenOptix, Inc.",' +
    '"DEST=DEST Corp.",' +
    '"DGC=Data General Corp.",' +
    '"DIGIDATA=Digi-Data Corporation",' +
    '"DigiIntl=Digi International",' +
    '"Digital=Digital Equipment Corporation (now HP)",' +
    '"DILOG=Distributed Logic Corp.",' +
    '"DISC=Document Imaging Systems Corp.",' +
    '"DLNET=Driveline",' +
    '"DNS=Data and Network Security",' +
    '"DotHill=Dot Hill Systems Corp.",' +
    '"DPT=Distributed Processing Technology",' +
    '"DSC=DigitalStream Corporation",' +
    '"DSI=Data Spectrum, Inc.",' +
    '"DSM=Deterner Steuerungs- und Maschinenbau GmbH & Co.",' +
    '"DTC QUME=Data Technology Qume",' +
    '"DXIMAGIN=DX Imaging",' +
    '"ECCS=ECCS, Inc.",' +
    '"ECMA=European Computer Manufacturers Association",' +
    '"elipsan=Elipsan UK Ltd.",' +
    '"Elms=Elms Systems Corporation",' +
    '"EMASS=EMASS, Inc.",' +
    '"EMC=EMC Corp.",' +
    '"EMTEC=EMTEC Magnetics",' +
    '"EMULEX=Emulex",' +
    '"ENERGY-B=Energybeam Corporation",' +
    '"ENGENIO=Engenio Information Technologies, Inc.",' +
    '"EPSON=Epson",' +
    '"EQLOGIC=EqualLogic",' +
    '"Eris/RSI=RSI Systems, Inc.",' +
    '"EuroLogc=Eurologic Systems Limited",' +
    '"evolve=Evolution Technologies, Inc",' +
    '"EXABYTE=Exabyte Corp.",' +
    '"EXATEL=Exatelecom Co., Ltd.",' +
    '"EXAVIO=Exavio, Inc.",' +
    '"FALCON=FalconStor, Inc.",' +
    '"FFEILTD=FujiFilm Electonic Imaging Ltd",' +
    '"Fibxn=Fiberxon, Inc.",' +
    '"FID=First International Digital, Inc.",' +
    '"FILENET=FileNet Corp.",' +
    '"FRAMDRV=FRAMEDRIVE Corp.",' +
    '"FUJI=Fuji Electric Co., Ltd. (Japan)",' +
    '"FUJIFILM=Fuji Photo Film, Co., Ltd.",' +
    '"FUJITSU=Fujitsu",' +
    '"FUNAI=Funai Electric Co., Ltd.",' +
    '"FUTURED=Future Domain Corp.",' +
    '"G&D=Giesecke & Devrient GmbH",' +
    '"Gadzoox=Gadzoox Networks, Inc.",' +
    '"GDI=Generic Distribution International",' +
    '"Gen_Dyn=General Dynamics",' +
    '"Generic=Generic Technology Co., Ltd.",' +
    '"GENSIG=General Signal Networks",' +
    '"GIGATAPE=GIGATAPE GmbH",' +
    '"GIGATRND=GigaTrend Incorporated",' +
    '"Global=Global Memory Test Consortium",' +
    '"Goidelic=Goidelic Precision, Inc.",' +
    '"GoldStar=LG Electronics Inc.",' +
    '"GOULD=Gould",' +
    '"HAGIWARA=Hagiwara Sys-Com Co., Ltd.",' +
    '"Heydays=Mazo Technology Co., Ltd.",' +
    '"HITACHI=Hitachi America Ltd or Nissei Sangyo America Ltd",' +
    '"HONEYWEL=Honeywell Inc.",' +
    '"HP=Hewlett Packard",' +
    '"HPQ=Hewlett Packard",' +
    '"HYUNWON=HYUNWON inc",' +
    '"i-cubed=i-cubed ltd.",' +
    '"IBM=International Business Machines",' +
    '"ICL=ICL",' +
    '"ICP=ICP vortex Computersysteme GmbH",' +
    '"IDE=International Data Engineering, Inc.",' +
    '"IFT=Infortrend Technology, Inc.",' +
    '"IGR=Intergraph Corp.",' +
    '"IMATION=Imation",' +
    '"IMPLTD=Integrated Micro Products Ltd.",' +
    '"IMPRIMIS=Imprimis Technology Inc.",' +
    '"INCITS=InterNational Committee for Information Technology",' +
    '"Indigita=Indigita Corporation",' +
    '"INITIO=Initio Corporation",' +
    '"INRANGE=INRANGE Technologies Corporation",' +
    '"INSITE=Insite Peripherals",' +
    '"integrix=Integrix, Inc.",' +
    '"INTEL=Intel Corporation",' +
    '"IOC=I/O Concepts, Inc.",' +
    '"IOMEGA=Iomega",' +
    '"iqstor=iQstor Networks, Inc.",' +
    '"ISi=Information Storage inc.",' +
    '"ISO=International Standards Organization",' +
    '"ITC=International Tapetronics Corporation",' +
    '"IVIVITY=iVivity, Inc.",' +
    '"IVMMLTD=InnoVISION Multimedia Ltd.",' +
    '"JPC Inc.=JPC Inc.",' +
    '"JVC=JVC Information Products Co.",' +
    '"KASHYA=Kashya, Inc.",' +
    '"KENNEDY=Kennedy Company",' +
    '"KENWOOD=KENWOOD Corporation",' +
    '"KODAK=Eastman Kodak",' +
    '"KONAN=Konan",' +
    '"KONICA=Konica Japan",' +
    '"KSCOM=KSCOM Co. Ltd.,",' +
    '"KUDELSKI=Nagravision SA - Kudelski Group",' +
    '"Kyocera=Kyocera Corporation",' +
    '"LAPINE=Lapine Technology",' +
    '"LASERDRV=LaserDrive Limited",' +
    '"LASERGR=Lasergraphics, Inc.",' +
    '"LEFTHAND=LeftHand Networks",' +
    '"Lexar=Lexar Media, Inc.",' +
    '"LG=LG Electronics Inc.",' +
    '"LGE=LG Electronics Inc.",' +
    '"LION=Lion Optics Corporation",' +
    '"LMS=Laser Magnetic Storage International Company",' +
    '"LSI=LSI Logic Corp.",' +
    '"LSILOGIC=LSI Logic Storage Systems, Inc.",' +
    '"LTO-CVE=Linear Tape - Open, Compliance Verification Entity",' +
    '"LUXPRO=Luxpro Corporation",' +
    '"Malakite=Malachite Technologies (New VID is: Sandial)",' +
    '"MATSHITA=Matsushita",' +
    '"MAXELL=Hitachi Maxell, Ltd.",' +
    '"MaxOptix=Maxoptix Corp.",' +
    '"MAXSTRAT=Maximum Strategy, Inc.",' +
    '"MAXTOR=Maxtor Corp.",' +
    '"MaXXan=MaXXan Systems, Inc.",' +
    '"MAYCOM=maycom Co., Ltd.",' +
    '"MBEAT=K-WON C&C Co.,Ltd",' +
    '"McDATA=McDATA Corporation",' +
    '"MDI=Micro Design International, Inc.",' +
    '"MEADE=Meade Instruments Corporation",' +
    '"MEII=Mountain Engineering II, Inc.",' +
    '"MELA=Mitsubishi Electronics America",' +
    '"MELCO=Mitsubishi Electric (Japan)",' +
    '"MEMOREX=Memorex Telex Japan Ltd.",' +
    '"MEMREL=Memrel Corporation",' +
    '"MEMTECH=MemTech Technology",' +
    '"MERIDATA=Oy Meridata Finland Ltd",' +
    '"METRUM=Metrum, Inc.",' +
    '"MHTL=Matsunichi Hi-Tech Limited",' +
    '"MICROBTX=Microbotics Inc.",' +
    '"MICROLIT=Microlite Corporation",' +
    '"MICROP=Micropolis",' +
    '"MICROTEK=Microtek Storage Corp",' +
    '"Minitech=Minitech (UK) Limited",' +
    '"Minolta=Minolta Corporation",' +
    '"MINSCRIB=Miniscribe",' +
    '"MITSUMI=Mitsumi Electric Co., Ltd.",' +
    '"MKM=Mitsubishi Kagaku Media Co., LTD.",' +
    '"MOSAID=Mosaid Technologies Inc.",' +
    '"MOTOROLA=Motorola",' +
    '"MPEYE=Touchstone Technology Co., Ltd",' +
    '"MPM=Mitsubishi Paper Mills, Ltd.",' +
    '"MPMan=MPMan.com, Inc.",' +
    '"MSFT=Microsoft Corporation",' +
    '"MSI=Micro-Star International Corp.",' +
    '"MST=Morning Star Technologies, Inc.",' +
    '"MTI=MTI Technology Corporation",' +
    '"MTNGATE=MountainGate Data Systems",' +
    '"MXI=Memory Experts International",' +
    '"nac=nac Image Technology Inc.",' +
    '"NAGRA=Nagravision SA - Kudelski Group",' +
    '"NAI=North Atlantic Industries",' +
    '"NAKAMICH=Nakamichi Corporation",' +
    '"NatInst=National Instruments",' +
    '"NatSemi=National Semiconductor Corp.",' +
    '"NCITS=InterNational Committee for Information Technology Standar",' +
    '"NCL=NCL America",' +
    '"NCR=NCR Corporation",' +
    '"Neartek=Neartek, Inc.",' +
    '"NEC=NEC",' +
    '"NETAPP=Network Appliance",' +
    '"Netcom=Netcom Storage",' +
    '"NEXSAN=Nexsan Technologies, Ltd.",' +
    '"NHR=NH Research, Inc.",' +
    '"NISCA=NISCA Inc.",' +
    '"NISHAN=Nishan Systems Inc.",' +
    '"NKK=NKK Corp.",' +
    '"NRC=Nakamichi Research Corporation",' +
    '"NSD=Nippon Systems Development Co.,Ltd.",' +
    '"NSM=NSM Jukebox GmbH",' +
    '"nStor=nStor Technologies, Inc.",' +
    '"NT=Northern Telecom",' +
    '"NUCONNEX=NuConnex",' +
    '"NUSPEED=NuSpeed, Inc.",' +
    '"OAI=Optical Access International",' +
    '"OCE=Oce Graphics",' +
    '"OKI=OKI Electric Industry Co.,Ltd (Japan)",' +
    '"Olidata=Olidata S.p.A.",' +
    '"OMI=Optical Media International",' +
    '"OMNIFI=Rockford Corporation - Omnifi Media",' +
    '"OMNIS=OMNIS Company (FRANCE)",' +
    '"Ophidian=Ophidian Designs",' +
    '"OPTIMEM=Cipher/Optimem",' +
    '"OPTOTECH=Optotech",' +
    '"ORANGE=Orange Micro, Inc.",' +
    '"ORCA=Orca Technology",' +
    '"OSI=Optical Storage International",' +
    '"OTL=OTL Engineering",' +
    '"pacdigit=Pacific Digital Corp",' +
    '"Packard=Parkard Bell",' +
    '"PARALAN=Paralan Corporation",' +
    '"PASCOsci=Pasco Scientific",' +
    '"PATHLGHT=Pathlight Technology, Inc.",' +
    '"PerStor=Perstor",' +
    '"PERTEC=Pertec Peripherals Corporation",' +
    '"PFTI=Performance Technology Inc.",' +
    '"PFU=PFU Limited",' +
    '"PHILIPS=Philips Electronics",' +
    '"PICO=Packard Instrument Company",' +
    '"Pillar=Pillar Data Systems",' +
    '"PIONEER=Pioneer Electronic Corp.",' +
    '"Pirus=Pirus Networks",' +
    '"PIVOT3=Pivot3, Inc.",' +
    '"PLASMON=Plasmon Data",' +
    '"PMCSIERA=PMC-Sierra",' +
    '"PRAIRIE=PrairieTek",' +
    '"PREPRESS=PrePRESS Solutions",' +
    '"PRESOFT=PreSoft Architects",' +
    '"PRESTON=Preston Scientific",' +
    '"PRIAM=Priam",' +
    '"PRIMAGFX=Primagraphics Ltd",' +
    '"PROCOM=Procom Technology",' +
    '"PROMISE=PROMISE TECHNOLOGY, Inc",' +
    '"PTI=Peripheral Technology Inc.",' +
    '"PTICO=Pacific Technology International",' +
    '"QIC=Quarter-Inch Cartridge Drive Standards, Inc.",' +
    '"QLogic=QLogic Corporation",' +
    '"QUALSTAR=Qualstar",' +
    '"QUANTEL=Quantel Ltd.",' +
    '"QUANTUM=Quantum Corp.",' +
    '"QUIX=Quix Computerware AG",' +
    '"R-BYTE=R-Byte, Inc.",' +
    '"RACALREC=Racal Recorders",' +
    '"RADITEC=Radikal Technologies Deutschland GmbH",' +
    '"RADSTONE=Radstone Technology",' +
    '"RASVIA=Rasvia Systems, Inc.",' +
    '"rave-mp=Go Video",' +
    '"Realm=Realm Systems",' +
    '"Revivio=Revivio, Inc.",' +
    '"RGI=Raster Graphics, Inc.",' +
    '"RHAPSODY=Rhapsody Networks, Inc.",' +
    '"RHS=Racal-Heim Systems GmbH",' +
    '"RICOH=Ricoh",' +
    '"RODIME=Rodime",' +
    '"RPS=RPS",' +
    '"RTI=Reference Technology",' +
    '"SAMSUNG=Samsung Electronics Co., Ltd.",' +
    '"SAN=Storage Area Networks, Ltd.",' +
    '"Sandial=Sandial Systems, Inc.",' +
    '"SANKYO=Sankyo Seiki",' +
    '"SANRAD=SANRAD Inc.",' +
    '"SANYO=SANYO Electric Co., Ltd.",' +
    '"SC.Net=StorageConnections.Net",' +
    '"SCIENTEK=SCIENTEK CORP",' +
    '"SCInc.=Storage Concepts, Inc.",' +
    '"SCREEN=Dainippon Screen Mfg. Co., Ltd.",' +
    '"SDI=Storage Dimensions, Inc.",' +
    '"SDS=Solid Data Systems",' +
    '"SEAGATE=Seagate",' +
    '"SEAGRAND=SEAGRAND In Japan",' +
    '"SEQUOIA=Sequoia Advanced Technologies, Inc.",' +
    '"Shinko=Shinko Electric Co., Ltd.",' +
    '"SIEMENS=Siemens",' +
    '"SigmaTel=SigmaTel, Inc.",' +
    '"SII=Seiko Instruments Inc.",' +
    '"SLI=Sierra Logic, Inc.",' +
    '"SMS=Scientific Micro Systems/OMTI",' +
    '"SNYSIDE=Sunnyside Computing Inc.",' +
    '"SONIC=Sonic Solutions",' +
    '"SoniqCas=SoniqCast",' +
    '"SONY=Sony Corporation Japan",' +
    '"SPD=Storage Products Distribution, Inc.",' +
    '"SPECIAL=Special Computing Co.",' +
    '"SPECTRA=Spectra Logic, a Division of Western Automation Labs, Inc.",' +
    '"SPERRY=Sperry (now Unisys Corp.)",' +
    '"Sterling=Sterling Diagnostic Imaging, Inc.",' +
    '"STK=Storage Technology Corporation",' +
    '"STONEFLY=StoneFly Networks, Inc.",' +
    '"STOR=StorageNetworks, Inc.",' +
    '"STORAPP=StorageApps, Inc.",' +
    '"STORCOMP=Storage Computer Corporation",' +
    '"STORM=Storm Technology, Inc.",' +
    '"StrmLgc=StreamLogic Corp.",' +
    '"SUMITOMO=Sumitomo Electric Industries, Ltd.",' +
    '"SUN=Sun Microsystems, Inc.",' +
    '"SUNCORP=SunCorporation",' +
    '"suntx=Suntx System Co., Ltd",' +
    '"SYMBIOS=Symbios Logic Inc.",' +
    '"SyQuest=SyQuest Technology, Inc.",' +
    '"SYSGEN=Sysgen",' +
    '"T-MITTON=Transmitton England",' +
    '"T11=INCITS Technical Committee T11",' +
    '"TALARIS=Talaris Systems, Inc.",' +
    '"TALLGRAS=Tallgrass Technologies",' +
    '"TANDBERG=Tandberg Data A/S",' +
    '"TANDEM=Tandem (now HP)",' +
    '"TANDON=Tandon",' +
    '"TCL=TCL Shenzhen ASIC MIcro-electronics Ltd",' +
    '"TDK=TDK Corporation",' +
    '"TEAC=TEAC Japan",' +
    '"TECOLOTE=Tecolote Designs",' +
    '"TEGRA=Tegra Varityper",' +
    '"Tek=Tektronix",' +
    '"TENTIME=Laura Technologies, Inc.",' +
    '"Test=Test new Vendor ID software - delete me!",' +
    '"TGEGROUP=TGE Group Co.,LTD.",' +
    '"TI-DSG=Texas Instruments",' +
    '"TiGi=TiGi Corporation",' +
    '"TMS=Texas Memory Systems, Inc.",' +
    '"TMS100=TechnoVas",' +
    '"TOLISGRP=The TOLIS Group",' +
    '"TOSHIBA=Toshiba Japan",' +
    '"TRIPACE=Tripace",' +
    '"TROIKA=Troika Networks, Inc.",' +
    '"TRULY=TRULY Electronics MFG. LTD.",' +
    '"UDIGITAL=United Digital Limited",' +
    '"ULTRA=UltraStor Corporation",' +
    '"UNISYS=Unisys",' +
    '"USCORE=Underscore, Inc.",' +
    '"USDC=US Design Corp.",' +
    '"VDS=Victor Data Systems Co., Ltd.",' +
    '"VERBATIM=Verbatim Corporation",' +
    '"VERITAS=VERITAS Software Corporation",' +
    '"VEXCEL=VEXCEL IMAGING GmbH",' +
    '"VicomSys=Vicom Systems, Inc.",' +
    '"VITESSE=Vitesse Semiconductor Corporation",' +
    '"VIXEL=Vixel Corporation",' +
    '"VMAX=VMAX Technologies Corp.",' +
    '"Vobis=Vobis Microcomputer AG",' +
    '"VRC=Vermont Research Corp.",' +
    '"Waitec=Waitec NV",' +
    '"WangDAT=WangDAT",' +
    '"WANGTEK=Wangtek",' +
    '"Wasabi=Wasabi Systems",' +
    '"WAVECOM=Wavecom",' +
    '"WD=Western Digital Technologies Inc.",' +
    '"WDC=Western Digital Technologies inc.",' +
    '"WDIGTL=Western Digital",' +
    '"WEARNES=Wearnes Technology Corporation",' +
    '"WSC0001=Wisecom, Inc.",' +
    '"X3=InterNational Committee for Information Technology Standar",' +
    '"XEBEC=Xebec Corporation",' +
    '"Xerox=Xerox Corporation",' +
    '"XIOtech=XIOtech Corporation",' +
    '"XYRATEX=Xyratex",' +
    '"YINHE=NUDT Computer Co.",' +
    '"YIXUN=Yixun Electronic Co.,Ltd.",' +
    '"YOTTA=YottaYotta, Inc.",' +
    '"Zarva=Zarva Digital Technology Co., Ltd.",' +
    '"ZETTA=Zetta Systems, Inc.",';

implementation

end.
